make embedding input optional for add and update nodes
abrenneke/rivet-plugin-chromadb pull request #2
Opened 2024-02-21 07:37 UTC by gengen1988

This allow use chroma as a key-value store. Useful when no other persist db available.

2024-02-21 19:24 UTC, abrenneke requested changes

2024-02-21 19:24 UTC, abrenneke commented on src/nodes/ChromaAddNode.ts
> +          embeddings: embedding ? [embedding] : [[]], // do no auto generate embedding
Are you sure we don't want to pass `undefined` like the other parameters? This looks like it will set the embeddings to an empty array, when the user might want them to be unchanged.

2024-02-21 19:29 UTC, abrenneke commented on src/nodes/ChromaAddNode.ts
> +          embeddings: embedding ? [embedding] : [[]], // do no auto generate embedding
(for the update node, that is)

2024-02-22 06:26 UTC, gengen1988 commented on src/nodes/ChromaAddNode.ts
> +          embeddings: embedding ? [embedding] : [[]], // do no auto generate embedding
I verified the behavior of chromadb and found some quirks. If the embedding value passed in is different from the embedding dimension in the collection, the embedding for this record will not change. This means that an empty array will never change the previous embedding.

The relevant documentation is here:
https://docs.trychroma.com/usage-guide#adding-data-to-a-collection

But the verification result is inconsistent with the documentation. After passing in embeddings of different dimensions, no exceptions are raised with the client. Maybe we should add some test cases to this project to ensure problems can be quickly located after chroma's behavior changes.

2024-02-22 07:04 UTC, gengen1988 commented on src/nodes/ChromaAddNode.ts
> +          embeddings: embedding ? [embedding] : [[]], // do no auto generate embedding
FYI: When passing `undefined` as embeddings, chroma will generate it with collection config, which may not as expect in rivet design.

2024-03-08 05:36 UTC, closed without merging